### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Zay-Ta** [Haruno19/starfetch#13]
I am using Fedora 35 and I have gcc installed but i can't compile starfetch

![Screenshot from 2022-05-02 21-53-10](https://user-images.githubusercontent.com/90143342/166260839-94a928fe-517a-44d7-84f0-f4ca29c8a21b.png)

**Comment by Zay-Ta** [comment]
The problem is solved! U need to install gcc-c++ in RHEL based distros

![Screenshot from 2022-05-02 22-14-27](https://user-images.githubusercontent.com/90143342/166264103-7dce3998-9ef8-48ed-a70d-b6614e5c14e8.png)

**Comment by Haruno19** [comment]
Nice! Maybe I'll add it in the readme file.

Issue closed
