### ISSUE TITLE
Add versioned tarball

### ISSUE THREAD

**Issue by nunotexbsd** [Haruno19/starfetch#20]
Is it possible to add version to tarball?
starfetch.tar.gz -> starfetch-0.0.2.tar.gz

This is usefull for port builders to access a static tarball.

An example: https://github.com/jordansissel/xdotool/releases

**Comment by Haruno19** [comment]
Sure thing!
Should be fine now?

**Comment by nunotexbsd** [comment]
`tar xzf starfetch-0.0.2.tar.gz` extracts to "starfetch" dir instead of "starfetch-0.0.2".
Could this be fixed?

Thanks

**Comment by Haruno19** [comment]
Release 0.0.3 should have fixed the problem! :)

**Comment by nunotexbsd** [comment]
Ok, nice!

Thanks
