### ISSUE TITLE
Put constellation data in different formats

### ISSUE THREAD

**Issue by papojari** [Haruno19/starfetch#3]
Right now all the data about the constellations is just in one Text file. I think putting the name, where it is and so on in JSON/TOML files would be a good design choice. How the stars relate to each other could be put into a coordinate system and then rendered by the program. This would feel like the proper way to me. Also many more features could be added because the data could now be accessed in an easier and more precise way.

**Comment by Haruno19** [comment]
Thank you for your feedback! 
I'm looking into improving the way the data is stored. The first step was made today (using a template file and fetching data from the constellations files), and now, for the next step I'm planning to use the JSON format as you suggested. I will try to implement a rendering system in the next few days.

Thank you for your support and help with this project!

**Comment by Haruno19** [comment]
starfetch now works with JSON formatted files (using the [nlohmann/json library](https://www.google.com/search?client=safari&rls=en&q=json+for+modern+c%2B%2B&ie=UTF-8&oe=UTF-8))! I'll put format details and proper credits into the README.md file
