### ISSUE TITLE
[Feature Request]  Color customization?

### ISSUE THREAD

**Issue by TheLastTeapot** [Haruno19/starfetch#32]
Is it possible to add color customization for all the elements? It looks really ugly with my terminal colors, but I need them the way they are for other things. Also, what font is used for the name above the art? It doesn't show up properly for me

**Comment by TheLastTeapot** [comment]
Alright, Thank you!

**Comment by Haruno19** [comment]
Thanks to @su8 with PR #33 stars are now colored! 

I'll still keep this issue open because I'd like to improve this feature further, implementing a parameter so that the user can manually select a color when launching starfetch, and maybe not only for the stars but for other things too (e.g. the text which now is printed as bold text maybe) :)

**Comment by su8** [comment]
It's not that hard to implement it - https://gist.github.com/JBlond/2fea43a3049b38287e5e9cefc87b2124

Just declare several global variables either std::string or **define** them and add another cli flag such as `-c` and test the input `argv[2]` for the requested color if it matches the **if** / **else if**. I tried to colorize the rest parameters but the side pipes and underlying pipes are not colorized.

**Comment by su8** [comment]
The lines that I added colorization are:

https://github.com/Haruno19/starfetch/blob/2a7f9914332ac39a87aa4e769f95ac48ec892903/src/starfetch.cpp#L91-L97

**Comment by su8** [comment]
Waited 1 hour and implemented the feature by myself.

**Comment by su8** [comment]
![Screenshot](https://user-images.githubusercontent.com/29376083/208080485-43f4f162-609a-4377-baf9-2291b177c1cf.png)

**Comment by Haruno19** [comment]
@su8 you're amazing :) 
Thank you a lot!!

**Comment by TheLastTeapot** [comment]
Thanks so much @su8! I don't know if you're aware, but it does only work when you specify a specific constellation.

**Comment by su8** [comment]
The color by default is **cyan** if you don't specify one with the `-c` option. If you run the program without specifying color and/or constellation it uses **cyan** color and some random constellation.

**Comment by su8** [comment]
Nice cath, it's fixed in https://github.com/Haruno19/starfetch/pull/35

**Comment by TheLastTeapot** [comment]
Thanks!

**Comment by TheLastTeapot** [comment]
it's still there? :(

**Comment by TheLastTeapot** [comment]
do I need specify something int the git command to make sure I have the most recent repo?
