### ISSUE TITLE
Please add starfetch in APT 

### ISSUE THREAD

**Issue by tildethinexxbisense** [Haruno19/starfetch#5]
Add it in APT so ubuntu users can use it easily

**Comment by Haruno19** [comment]
Hi! As [stated](https://github.com/Haruno19/starfetch/issues/1#issuecomment-1092772582) under issue #1, I'm working on adding starfetch to other repositories to make it more accessible to users. 

I'll close this issue and edit issue #1 to make it more general. From now on, I'll post updates on this matter (_package managers/repositories_) there. Please refer to issue #1  for updates on your request as well.
